### ISSUE TITLE
Tokens: Change design token "categories" to the Theo-supported categories

### ISSUE THREAD

**Issue by clepore** [infor-design/design-system#204]
We should update the design token categories to the (now documented) [Theo-supported categories](https://github.com/salesforce-ux/theo#supported-categories) so we can generate a "colors" [sample page](https://github.com/salesforce-ux/theo#html).

Also, since we are changing the categories, and the website relies on these categories for sorting the design tokens, we should shift the current category values to meta data per property.

Current state:
```
button-default-bg-color:
  value: "{!COLOR_DEFAULT}"
  type: "color"
  category: button
```
Desired state:
```
button-default-bg-color:
  value: "{!COLOR_DEFAULT}"
  type: "color"
  category: "background-color"    // specific from Theo's supported list
  meta:
    component: button
```
